# Generated by Django 5.0.4 on 2024-04-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
