# Generated by Django 5.0.4 on 2024-04-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_group_description_team_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryadmin',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='group',
            name='countries',
        ),
        migrations.AddField(
            model_name='countryadmin',
            name='country',
            field=models.ForeignKey(default='Default Country', on_delete=django.db.models.deletion.CASCADE, to='organization.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.country'),
        ),
    ]
