# Generated by Django 5.0.4 on 2024-05-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_group_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling')], max_length=3)),
                ('timezone', models.CharField(choices=[('EST', 'Eastern Standard Time'), ('CST', 'Central Standard Time'), ('MST', 'Mountain Standard Time'), ('PST', 'Pacific Standard Time'), ('UTC', 'Coordinated Universal Time')], max_length=50)),
                ('language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian')], max_length=50)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization.country')),
            ],
        ),
    ]
