# Generated by Django 5.0.4 on 2024-05-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_countrysetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrysetting',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'Pound Sterling'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SEK', 'Swedish Krona'), ('NZD', 'New Zealand Dollar')], max_length=3),
        ),
        migrations.AlterField(
            model_name='countrysetting',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('ZH', 'Chinese'), ('JA', 'Japanese')], max_length=50),
        ),
        migrations.AlterField(
            model_name='countrysetting',
            name='timezone',
            field=models.CharField(choices=[('EST', 'Eastern Standard Time'), ('CST', 'Central Standard Time'), ('MST', 'Mountain Standard Time'), ('PST', 'Pacific Standard Time'), ('UTC', 'Coordinated Universal Time'), ('GMT', 'Greenwich Mean Time'), ('CET', 'Central European Time (GMT+1)'), ('EET', 'Eastern European Time (GMT+2)'), ('IST', 'Indian Standard Time (GMT+5:30)'), ('CST', 'China Standard Time (GMT+8)'), ('JST', 'Japan Standard Time (GMT+9)'), ('AEST', 'Australian Eastern Standard Time (GMT+10)')], max_length=50),
        ),
    ]
