# Generated by Django 5.0.4 on 2024-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('name2', models.CharField(default='', max_length=100)),
                ('vat', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('postcode', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=100)),
                ('street_name', models.CharField(default='', max_length=200)),
                ('street_number', models.CharField(default='', max_length=20)),
                ('industry', models.CharField(default='', max_length=200)),
                ('primary_role', models.CharField(default='', max_length=100)),
                ('secondary_role', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
