# Generated by Django 5.0.4 on 2024-04-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0002_alter_businesspartner_user'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contact'),
        ),
    ]
