# Generated by Django 5.0.4 on 2024-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspartner',
            name='industry',
            field=models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Healthcare', 'Healthcare'), ('Technology', 'Technology'), ('Finance', 'Finance'), ('Education', 'Education'), ('Construction', 'Construction'), ('Transportation', 'Transportation'), ('Agriculture', 'Agriculture'), ('Energy', 'Energy')], default='Manufacturing', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='primary_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant'), ('partner', 'Partner')], default='customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='businesspartner',
            name='secondary_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant'), ('partner', 'Partner'), ('-', '-')], default='customer', max_length=100),
        ),
    ]
