# Generated by Django 5.0.4 on 2024-05-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
