# Generated by Django 5.0.4 on 2024-05-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_description', to='hr.position'),
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
