# Generated by Django 5.0.4 on 2024-05-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_description_position_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='description',
        ),
    ]
