# Generated by Django 5.0.4 on 2024-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='todo_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
