# Generated by Django 5.0.4 on 2024-04-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_completed_items_task_todo_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_items',
        ),
        migrations.RemoveField(
            model_name='task',
            name='todo_list',
        ),
    ]
