# Generated by Django 5.0.4 on 2024-04-18 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('name2', models.CharField(default='', max_length=100)),
                ('vat', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('countries', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('postcode', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=100)),
                ('street_name', models.CharField(default='', max_length=200)),
                ('street_number', models.CharField(default='', max_length=20)),
                ('industry', models.CharField(default='', max_length=200)),
                ('primary_role', models.CharField(default='', max_length=100)),
                ('secondary_role', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('academic_title', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('title', models.CharField(choices=[('Manager', 'Manager'), ('Director', 'Director'), ('Executive', 'Executive'), ('Other', 'Other')], max_length=50)),
                ('job_function', models.CharField(choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('IT', 'IT'), ('Finance', 'Finance'), ('HR', 'HR'), ('Other', 'Other')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('preferred_communication', models.CharField(blank=True, choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Text', 'Text'), ('In-Person', 'In-Person')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.businesspartner')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('probability', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('finished', 'finished'), ('in progress', 'in progress')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.businesspartner')),
            ],
        ),
    ]
