# Generated by Django 5.0.4 on 2024-04-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant'), ('partner', 'Partner')], default='customer', max_length=100, verbose_name='Primary Role'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='secondary_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant'), ('partner', 'Partner'), ('admin', 'Admin')], default='customer', max_length=100, verbose_name='Secondary Role'),
        ),
    ]
