# Generated by Django 5.0.4 on 2024-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_customer_secondary_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('finished', 'finished'), ('in progress', 'in progress')], max_length=50),
        ),
    ]
