# Generated by Django 5.0.4 on 2024-04-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_opportunity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='assigned_to',
        ),
    ]
