# Generated by Django 5.0.4 on 2024-04-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_opportunity_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='assigned_to',
            new_name='assigned_to_user',
        ),
    ]
