# Generated by Django 5.0.4 on 2024-04-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_rename_assigned_to_opportunity_assigned_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='assigned_to_user',
        ),
    ]
