# Generated by Django 5.0.4 on 2024-04-21 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_opportunity_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='job_function',
            new_name='department',
        ),
    ]
