# Generated by Django 5.0.4 on 2024-04-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_rename_job_function_contact_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('IT', 'IT'), ('Finance', 'Finance'), ('HR', 'HR'), ('Other', 'Other'), ('---', '---')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Director', 'Director'), ('Executive', 'Executive'), ('Other', 'Other'), ('---', '---')], max_length=50),
        ),
    ]
