# Generated by Django 5.0.4 on 2024-04-21 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_contact_department_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_contacted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
