# Generated by Django 5.0.4 on 2024-04-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_partner', '0001_initial'),
        ('crm', '0014_alter_contact_last_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='business_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='business_partner.businesspartner'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='business_partner.businesspartner'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='business_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='business_partner.businesspartner'),
        ),
        migrations.DeleteModel(
            name='BusinessPartner',
        ),
    ]
