# Generated by Django 5.0.4 on 2024-04-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('crm', '0015_alter_contact_business_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='contact.contact'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('finished', 'Finished'), ('in_progress', 'In Progress')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
